# kcare0 param.yaml
lm_control_node:
  ros__parameters:
    port: "/dev/ttyLM"
    baudrate: 19200
    offset_position: 108.0
    global_speed: 5000
    initial_speed: 1000
    elevation_range: [113.0, 680.0]
    home_position: 118.0
